# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = '<i class="fas fa-home"></i>'
  url = ""
  weight = 10

[[main]]
  name = "文档"
  url = "#docs"
  weight = 20

[[main]]
  name = "关于"
  url = "#about"
  weight = 30
