name: Build website

# Run for PRs and the master branch
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the website
        run: make all

      - name: Deploy to seismo-learn.github.io
        if: success() && github.event_name == 'push'
        # peaceiris/actions-gh-pages@v3.7.3
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          # personal token can be generated at https://github.com/settings/tokens,
          # and added to "Settings"->"Secrets"
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: seismo-learn/seismo-learn.github.io
          publish_branch: main
          publish_dir: ./public
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
