#
# Build and deploy the documentation
#
name: Deploy

# Run on main branch only
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 0.98.0
          extended: true

      - name: Build the website
        run: make all

      - name: Deploy to seismo-learn.github.io
        uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b
        with:
          # personal token is needed here because it's pushing to an external repository.
          # personal token can be generated at https://github.com/settings/tokens,
          # and added to https://github.com/organizations/seismo-learn/settings/secrets/actions
          personal_token: ${{ secrets.TOKEN_DOCUMENT_DEPLOY }}
          external_repository: seismo-learn/seismo-learn.github.io
          publish_branch: main
          publish_dir: ./public
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
