#
# Build and deploy the documentation
#
name: Deploy

# Run on main branch only
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.80.0
          extended: true

      - name: Build the website
        run: make all

      - name: Deploy to seismo-learn.github.io
        # peaceiris/actions-gh-pages@v3.7.3
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          # personal token is needed here because it's pushing to an external repository.
          # personal token can be generated at https://github.com/settings/tokens,
          # and added to https://github.com/organizations/seismo-learn/settings/secrets/actions
          personal_token: ${{ secrets.TOKEN_DOCUMENT_DEPLOY }}
          external_repository: seismo-learn/seismo-learn.github.io
          publish_branch: main
          publish_dir: ./public
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
